# Generated by Django 3.0.8 on 2020-07-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_financials_ratios_niperebt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Financials_Ratios',
        ),
    ]
