# Generated by Django 3.0.8 on 2020-07-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_delete_financials_ratios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financials_Ratios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('ratio_class', models.CharField(max_length=500)),
                ('priceToBookRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('priceToSalesRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('priceEarningsRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('priceToFreeCashFlowsRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('priceToOperatingCashFlowsRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('priceCashFlowRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('priceEarningsToGrowthRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('priceSalesRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('dividendYield', models.DecimalField(decimal_places=4, max_digits=12)),
                ('enterpriseValueMultiple', models.DecimalField(decimal_places=4, max_digits=12)),
                ('priceFairValue', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ebtperEBIT', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ebitperRevenue', models.DecimalField(decimal_places=4, max_digits=12)),
                ('grossProfitMargin', models.DecimalField(decimal_places=4, max_digits=12)),
                ('operatingProfitMargin', models.DecimalField(decimal_places=4, max_digits=12)),
                ('pretaxProfitMargin', models.DecimalField(decimal_places=4, max_digits=12)),
                ('netProfitMargin', models.DecimalField(decimal_places=4, max_digits=12)),
                ('effectiveTaxRate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('returnOnAssets', models.DecimalField(decimal_places=4, max_digits=12)),
                ('returnOnEquity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('returnOnCapitalEmployed', models.DecimalField(decimal_places=4, max_digits=12)),
                ('nIperEBT', models.DecimalField(decimal_places=4, max_digits=12)),
                ('eBTperEBIT', models.DecimalField(decimal_places=4, max_digits=12)),
                ('eBITperRevenue', models.DecimalField(decimal_places=4, max_digits=12)),
                ('payablesTurnover', models.DecimalField(decimal_places=4, max_digits=12)),
                ('inventoryTurnover', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fixedAssetTurnover', models.DecimalField(decimal_places=4, max_digits=12)),
                ('assetTurnover', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currentRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quickRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cashRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('daysOfSalesOutstanding', models.DecimalField(decimal_places=4, max_digits=12)),
                ('daysOfInventoryOutstanding', models.DecimalField(decimal_places=4, max_digits=12)),
                ('operatingCycle', models.DecimalField(decimal_places=4, max_digits=12)),
                ('daysOfPayablesOutstanding', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cashConversionCycle', models.DecimalField(decimal_places=4, max_digits=12)),
                ('debtRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('debtEquityRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('longtermDebtToCapitalization', models.DecimalField(decimal_places=4, max_digits=12)),
                ('totalDebtToCapitalization', models.DecimalField(decimal_places=4, max_digits=12)),
                ('interestCoverage', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cashFlowToDebtRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('companyEquityMultiplier', models.DecimalField(decimal_places=4, max_digits=12)),
                ('operatingCashFlowPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('freeCashFlowPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cashPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('payoutRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('receivablesTurnover', models.DecimalField(decimal_places=4, max_digits=12)),
                ('operatingCashFlowSalesRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('freeCashFlowOperatingCashFlowRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cashFlowCoverageRatios', models.DecimalField(decimal_places=4, max_digits=12)),
                ('shortTermCoverageRatios', models.DecimalField(decimal_places=4, max_digits=12)),
                ('capitalExpenditureCoverageRatios', models.DecimalField(decimal_places=4, max_digits=12)),
                ('dividendpaidAndCapexCoverageRatios', models.DecimalField(decimal_places=4, max_digits=12)),
                ('dividendPayoutRatio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('company_ratios_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios', to='company.Company')),
            ],
        ),
    ]
