# Generated by Django 3.0.8 on 2020-07-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.CharField(default='Palo Alto, CA', max_length=100),
        ),
    ]
