# Generated by Django 3.0.8 on 2020-07-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
