# Generated by Django 3.0.8 on 2020-07-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_employee_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyURL',
            field=models.CharField(default='www.google.com', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='competitors',
            field=models.CharField(default='Red Hat', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='overview',
            field=models.CharField(default='Red Hat', max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='ownership',
            field=models.CharField(default='public', max_length=100),
        ),
    ]
