# Generated by Django 3.0.8 on 2020-07-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_financials_ratios_financials_stockchart_financials_trends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterURL', models.CharField(max_length=1000)),
                ('company_trends_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Financials_Trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('revenueGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('grossProfitGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ebitgrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('operatingIncomeGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('netIncomeGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('epsgrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('epsdilutedGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('weightedAverageSharesGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('weightedAverageSharesDilutedGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('dividendsperShareGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('operatingCashFlowGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('freeCashFlowGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tenYRevenueGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fiveYRevenueGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threeYRevenueGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tenYOperatingCFGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fiveYOperatingCFGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threeYOperatingCFGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tenYNetIncomeGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fiveYNetIncomeGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threeYNetIncomeGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tenYShareholdersEquityGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fiveYShareholdersEquityGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threeYShareholdersEquityGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tenYDividendperShareGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fiveYDividendperShareGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threeYDividendperShareGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('receivablesGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('inventoryGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('assetGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('bookValueperShareGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('debtGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('rdexpenseGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('company_trends_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Financials_StockChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chartURL', models.CharField(default='www.google.com', max_length=1000)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_chart', to='company.Company')),
            ],
        ),
    ]
