# Generated by Django 3.0.8 on 2020-07-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_financials_stockchart_financials_trends_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Lines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line', models.CharField(max_length=500)),
                ('company_desc', models.CharField(max_length=1000)),
                ('friendly_desc', models.CharField(max_length=1000)),
                ('explainations', models.CharField(max_length=1000)),
                ('company_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_products', to='company.Company')),
            ],
        ),
    ]
