# Generated by Django 3.0.8 on 2020-07-20 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_product_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line2', models.CharField(max_length=500)),
                ('product_name', models.CharField(max_length=500)),
                ('company_desc', models.CharField(max_length=1000)),
                ('friendly_desc', models.CharField(max_length=1000)),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_ind_products', to='company.Company')),
                ('parent_product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_lines', to='company.Product_Lines')),
            ],
        ),
    ]
