# Generated by Django 3.0.8 on 2020-07-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_productspecific'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials_trends',
            name='sgaexpensesGrowth',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
