# Generated by Django 3.0.8 on 2020-07-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_financials_trends_sgaexpensesgrowth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financials_ratios',
            name='ratio_class',
        ),
    ]
