# Generated by Django 3.0.8 on 2020-07-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_remove_financials_ratios_ratio_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financials_trends',
            name='company_trends_name',
        ),
        migrations.DeleteModel(
            name='Financials_Ratios',
        ),
        migrations.DeleteModel(
            name='Financials_Trends',
        ),
    ]
