# Generated by Django 3.0.8 on 2020-07-21 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200721_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_Trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('ratio_name', models.CharField(max_length=1000)),
                ('ratio_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('company_fin_trends_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_trends', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Financial_Ratios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('ratio_name', models.CharField(max_length=1000)),
                ('ratio_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('company_fin_ratios_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_ratios', to='company.Company')),
            ],
        ),
    ]
