# Generated by Django 3.0.8 on 2020-07-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_financial_ratios_financial_trends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial_trends',
            name='company_fin_trends_name',
        ),
        migrations.DeleteModel(
            name='Financial_Ratios',
        ),
        migrations.DeleteModel(
            name='Financial_Trends',
        ),
    ]
