# Generated by Django 3.0.8 on 2020-07-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_financial_ratios_financial_trends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True)),
                ('definition', models.CharField(max_length=1000)),
                ('example', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Spec_Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_spec_vocab', to='company.ProductSpecific')),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_term_id', to='company.Vocab')),
            ],
        ),
    ]
