# Generated by Django 3.0.8 on 2020-07-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_product_spec_vocab_vocab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab',
            old_name='example',
            new_name='useful_example',
        ),
    ]
