# Generated by Django 3.0.8 on 2020-07-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20200723_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_spec_vocab',
            old_name='specific_product_id',
            new_name='specific_product',
        ),
        migrations.RenameField(
            model_name='product_spec_vocab',
            old_name='term_id',
            new_name='term',
        ),
    ]
