# Generated by Django 3.0.8 on 2020-07-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20200723_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Line_Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_line_vocab', to='company.Product_Lines')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_id', to='company.Vocab')),
            ],
        ),
    ]
