# Generated by Django 3.0.8 on 2020-07-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_product_line_vocab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_spec_vocab',
            name='specific_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_spec_vocab', to='company.Product_Lines'),
        ),
    ]
