# Generated by Django 3.0.8 on 2020-08-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20200723_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fiscal_year_end',
            field=models.CharField(default='Jan 1 2020', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
