# Generated by Django 3.0.8 on 2020-08-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20200811_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(max_length=4)),
                ('grossProfitGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ebitgrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('operatingIncomeGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('netIncomeGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('epsgrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('epsdilutedGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('weightedAverageSharesGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('weightedAverageSharesDilutedGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('dividendsperShareGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('operatingCashFlowGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('freeCashFlowGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tenYRevenueGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fiveYRevenueGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threeYRevenueGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tenYOperatingCFGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fiveYOperatingCFGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threeYOperatingCFGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tenYNetIncomeGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fiveYNetIncomeGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threeYNetIncomeGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tenYShareholdersEquityGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fiveYShareholdersEquityGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threeYShareholdersEquityGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tenYDividendperShareGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fiveYDividendperShareGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threeYDividendperShareGrowthPerShare', models.DecimalField(decimal_places=4, max_digits=12)),
                ('receivablesGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('inventoryGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('assetGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('bookValueperShareGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('debtGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('rdexpenseGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sgaexpensesGrowth', models.DecimalField(decimal_places=4, max_digits=12)),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_trends', to='company.Company')),
            ],
        ),
    ]
