# Generated by Django 3.0.8 on 2020-08-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_fin_trends'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_trends',
            name='revenueGrowth',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fin_trends',
            name='fiscal_year',
            field=models.IntegerField(),
        ),
    ]
