# Generated by Django 3.0.8 on 2020-08-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20200813_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fin_Trends',
        ),
    ]
