# Generated by Django 3.0.8 on 2020-08-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_delete_fin_trends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.CharField(max_length=1000)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fiscal_year', models.IntegerField()),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_trends', to='company.Company')),
            ],
        ),
    ]
