# Generated by Django 3.0.8 on 2020-08-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_fin_ratios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Newsfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsslink', models.CharField(max_length=1000)),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_news', to='company.Company')),
            ],
        ),
    ]
