# Generated by Django 3.0.8 on 2020-09-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_trackinghistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackinghistory',
            options={'ordering': ['-viewed_on'], 'verbose_name': 'TrackingHistory', 'verbose_name_plural': 'TrackingHistory'},
        ),
        migrations.AlterModelOptions(
            name='vocab',
            options={'verbose_name_plural': 'Vocab'},
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='ip_address',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
