# Generated by Django 3.0.8 on 2020-09-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_auto_20200922_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='sys_path',
            field=models.CharField(blank=True, default='path', max_length=1000, null=True),
        ),
    ]
