# Generated by Django 3.0.8 on 2020-09-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_trackinghistory_sys_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cagetory', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vocab',
            name='useful_example',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
