# Generated by Django 3.0.8 on 2020-09-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_auto_20200924_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab_category',
            old_name='cagetory',
            new_name='catergory',
        ),
    ]
