# Generated by Django 3.0.8 on 2020-09-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_auto_20200924_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab_category',
            old_name='catergory',
            new_name='category',
        ),
    ]
