# Generated by Django 3.0.8 on 2020-09-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_auto_20200924_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab_category',
            name='term',
            field=models.ManyToManyField(blank=True, to='company.Vocab', verbose_name='Vocab'),
        ),
    ]
