# Generated by Django 3.0.8 on 2020-09-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_vocab_category_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='product_page_url',
            field=models.CharField(default='www.google.com', max_length=100),
        ),
    ]
