# Generated by Django 3.0.8 on 2020-09-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_company_product_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='competitors',
            field=models.CharField(default='Red Hat', max_length=1000),
        ),
    ]
