# Generated by Django 3.0.8 on 2020-10-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_auto_20200930_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(max_length=1000, unique=True)),
            ],
        ),
    ]
